version: '3.8'

services:
  order-service:
    build: ./microservices/order-service
    ports:
      - "5001:5001"
    volumes:
      - ./Database:/app/Database
    environment:
      - DATABASE_PATH=/app/Database/ecommerce.db

  product-service:
    build: ./microservices/product-service
    ports:
      - "5000:5000"
    volumes:
      - ./Database:/app/Database
    environment:
      - DATABASE_PATH=/app/Database/ecommerce.db

  user-service:
    build: ./microservices/user-service
    ports:
      - "5002:5002"
    volumes:
      - ./Database:/app/Database
    environment:
      - DATABASE_PATH=/app/Database/ecommerce.db

  analytics-service:
    build: ./microservices/analytics-service
    ports:
      - "5003:5003"
    volumes:
      - ./Database:/app/Database
    environment:
      - DATABASE_PATH=/app/Database/ecommerce.db
    command: uvicorn app:app --host 0.0.0.0 --port 5003